---
name: on-demand-scans-scanner-profiles
introduced_by_url:
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/241111
group: group::dynamic analysis
type: development
default_enabled: false