---
name: run_sidekiq_sampler
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/50710
rollout_issue_url: 
milestone: '13.8'
type: development
group: group::memory
default_enabled: false
