.tests-metadata-state:
  image: ruby:2.7
  before_script:
    - source scripts/utils.sh
  artifacts:
    expire_in: 31d
    paths:
      - knapsack/
      - rspec_flaky/
      - rspec_profiling/
      - crystalball/packed-mapping.json.gz

retrieve-tests-metadata:
  extends:
    - .tests-metadata-state
    - .test-metadata:rules:retrieve-tests-metadata
  stage: prepare
  script:
    - install_gitlab_gem
    - source ./scripts/rspec_helpers.sh
    - retrieve_tests_metadata

update-tests-metadata:
  extends:
    - .tests-metadata-state
    - .test-metadata:rules:update-tests-metadata
  stage: post-test
  needs:
    - rspec-child-pipeline
    - setup-test-env
    - rspec frontend_fixture
    - rspec-ee frontend_fixture
  script:
    - install_gitlab_gem
    - download_artifacts_from_downstream_job rspec-child-pipeline rspec-gather-artifacts
    - run_timed_command "retry gem install fog-aws mime-types activesupport rspec_profiling postgres-copy --no-document"
    - source ./scripts/rspec_helpers.sh
    - update_tests_metadata
    - update_tests_mapping
